PUT file://C:/Users/prave/OneDrive/Desktop/CartFlow/CartFlow/data/raw/*.csv @RAW_STAGE AUTO_COMPRESS=TRUE OVERWRITE=TRUE;



list @RAW_STAGE;

USE WAREHOUSE warehouse_snow;
USE DATABASE CARTFLOW_DB;
USE SCHEMA BRONZE;

COPY INTO ECOMMERCE_CONSUMER_BEHAVIOUR
FROM @RAW_STAGE/ecommerce_consumer_behaviour.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO ORDER_DATES
FROM @RAW_STAGE/order_dates.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO ORDER_ITEMS_QTY
FROM @RAW_STAGE/order_items_qty.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO ORDER_PAYMENTS
FROM @RAW_STAGE/order_payments.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO ORDER_REVIEWS
FROM @RAW_STAGE/order_reviews.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO PRODUCT_PRICING
FROM @RAW_STAGE/product_pricing.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO SELLERS
FROM @RAW_STAGE/sellers.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');


--to check
SELECT COUNT(*) FROM ECOMMERCE_CONSUMER_BEHAVIOUR;
SELECT COUNT(*) FROM ORDER_DATES;
SELECT COUNT(*) FROM ORDER_ITEMS_QTY;
SELECT COUNT(*) FROM ORDER_PAYMENTS;
SELECT COUNT(*) FROM ORDER_REVIEWS;
SELECT COUNT(*) FROM PRODUCT_PRICING;
SELECT COUNT(*) FROM SELLERS;

